ci:
  autoupdate_schedule: monthly

default_language_version:
  python: python3.13

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-json
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-toml
  - id: end-of-file-fixer
    exclude: |
      (?x)^(
        example/example/static/ext/debug\.js
        |src/django_htmx/static/django_htmx/htmx\.min\.js
      )$
  - id: trailing-whitespace
- repo: https://github.com/crate-ci/typos
  rev: edb4e206047e89b93ebe08f1a2ccc3d581a70cc7  # frozen: v1
  hooks:
  - id: typos
- repo: https://github.com/tox-dev/pyproject-fmt
  rev: 8184a5b72f4a8fcd003b041ecb04c41a9f34fd2b  # frozen: v2.6.0
  hooks:
  - id: pyproject-fmt
- repo: https://github.com/tox-dev/tox-ini-fmt
  rev: 4e2cb0e98735e1a57a027d9440b91663e31d10b0  # frozen: 1.6.0
  hooks:
  - id: tox-ini-fmt
- repo: https://github.com/rstcheck/rstcheck
  rev: 27258fde1ee7d3b1e6a7bbc58f4c7b1dd0e719e5  # frozen: v6.2.5
  hooks:
  - id: rstcheck
    additional_dependencies:
    - sphinx==8.1.3
    - tomli==2.2.1
- repo: https://github.com/sphinx-contrib/sphinx-lint
  rev: ff671d6a030a3141634793e6d1e8909ab6091830  # frozen: v1.0.0
  hooks:
  - id: sphinx-lint
- repo: https://github.com/adamchainz/django-upgrade
  rev: ae0267712cd26a78cb99c40ab4a01984072dcd29  # frozen: 1.28.0
  hooks:
  - id: django-upgrade
- repo: https://github.com/adamchainz/blacken-docs
  rev: dda8db18cfc68df532abf33b185ecd12d5b7b326  # frozen: 1.20.0
  hooks:
  - id: blacken-docs
    additional_dependencies:
    - black==25.1.0
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: 60ef368a6f48dfb4317651017f66dbb055241a6c  # frozen: v0.12.12
  hooks:
    - id: ruff-check
      args: [ --fix ]
    - id: ruff-format
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 412de98d50e846f31ea6f4b0ad036f2c24a7a024  # frozen: v1.17.1
  hooks:
  - id: mypy
    additional_dependencies:
    - django-stubs==5.1.2
    - inline-snapshot
    - types-python-dateutil
- repo: https://github.com/adamchainz/djade-pre-commit
  rev: 47481957f135f6af9121b2af9c415155d260cc8e  # frozen: 1.6.0
  hooks:
  - id: djade
